apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: api-gateway
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
      ignoreChanges: true
  artifacts:
    - image: api-gw-skaffold
      context: .
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - api-gw-skaffold
        squash: false
