coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      auth-service:
        paths:
          - "auth-service/**"
        flags:
          - auth-service
      todo-service:
        paths:
          - "todo-service/**"
        flags:
          - todo-service
    patch:
      auth-service:
        paths:
          - "auth-service/**"
        flags:
          - auth-service
      todo-service:
        paths:
          - "todo-service/**"
        flags:
          - todo-service

flags:
  auth-service:
    paths:
      - "auth-service/**"
    carryforward: true
  todo-service:
    paths:
      - "todo-service/**"
    carryforward: true

comment:
  show_carryforward_flags: true
