version: "3.9"

services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-ui:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

networks:
  default:
    name: todo-network

volumes:
  postgres-data:
