global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gw:3030"]

  - job_name: auth-service
    static_configs:
      - targets: ["auth-service:3030"]

  - job_name: todo-service
    static_configs:
      - targets: ["todo-service:3030"]
