version: "3.9"

services:
  nats:
    image: nats

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/dev/prometheus.yml:/etc/prometheus/prometheus.yml

  postgres-ui:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  api-gw:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TRANSPORTER_URL: nats://nats:4222
      ENABLE_METRICS: true
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - nats

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TRANSPORTER_URL: nats://nats:4222
      DB_HOST: postgres
      ENABLE_METRICS: true
    depends_on:
      - postgres
      - nats

  todo-service:
    build:
      context: ./todo-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TRANSPORTER_URL: nats://nats:4222
      DB_HOST: postgres
      ENABLE_METRICS: true
    depends_on:
      - postgres
      - nats

networks:
  default:
    name: todo-network-dev

volumes:
  postgres-data-dev:
