name: Push auth-service image to ecr

on:
  push:
    branches:
      - master
    paths:
      - "auth-service/**"

jobs:
  push_to_ecr:
    name: psuh to ecr
    runs-on: ubuntu-latest
    env:
      PROJECT: auth-service
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: set image name
        run: echo "IMAGE=${{ secrets.DOCKER_REGISTRY }}/$PROJECT" >> $GITHUB_ENV

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: build and push image
        run: |
          cd $PROJECT
          skaffold build -p production

      - name: tag image (latest and branch name)
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker tag $IMAGE:$TAG $IMAGE:$GITHUB_REF_NAME

      - name: push tag (latest and branch name)
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:$GITHUB_REF_NAME
