name: Run tests for auth-service

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "auth-service/**"

jobs:
  test_auth-service:
    name: test-auth-service
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install dependencies
        run: npm ci --prefix ./auth-service

      - name: build application
        run: npm run build --prefix ./auth-service

      - name: test application
        run: npm run test --prefix ./auth-service
