name: Run tests for todo-service

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "todo-service/**"

jobs:
  test_todo-service:
    name: test-todo-service
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: todo-service
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install dependencies
        run: npm ci --prefix ./todo-service

      - name: build application
        run: npm run build --prefix ./todo-service

      - name: test application
        run: npm run test --prefix ./todo-service

      - name: publish coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # requried for private repos only
          files: ./todo-service/coverage/coverage-final.json
          flags: todo-service
          name: todo-service
          fail_ci_if_error: true
